"""add security question hashes

Revision ID: 01b31b31a604
Revises: 7be987cd1b10
Create Date: 2026-09-06 06:49:14.444028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b31b31a604'
down_revision: Union[str, Sequence[str], None] = '7be987cd1b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_book_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('favorite_person_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_person_hash')
    op.drop_column('users', 'favorite_book_hash')
    # ### end Alembic commands ###
