"""add company id to jobs

Revision ID: ce96a8dc5b63
Revises: 01b31b31a604
Create Date: 2026-09-06 07:04:32.431085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce96a8dc5b63'
down_revision: Union[str, Sequence[str], None] = '01b31b31a604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['recruiter_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_column('jobs', 'company_id')
    # ### end Alembic commands ###
